title: [Archivio sull'incendio in Australia]
description: [Un archivio di filmati YouTube sugli incendi in Australia nel 2019 e 2020.]
logo: https://static01.nyt.com/images/2020/01/31/world/31ozf-fires-kangaroo/31ozf-fires-kangaroo-mobileMasterAt3x-v2.jpg
theme: jekyll-theme-minimal
